---
- name: install docker
  yum: name=docker state=present

- name: start docker service
  service: name=docker state=started

- name: download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: '755'